services:
  load-balancer:
    build: ./load-balancer
    ports:
      - "18888:18888" # Expose the load balancer on port 18811
    depends_on:
      - rpyc-server1
      - rpyc-server2

  rpyc-server1:
    build: ./server
    depends_on:
      - redis

    volumes:
      - ./scripts:/app/scripts
  rpyc-server2:
    build: ./server
    depends_on:
      - redis
    volumes:
      - ./scripts:/app/scripts


  rpyc-client:
    build: ./client
    depends_on:
      - load-balancer

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379" # Expose Redis on port 6379
