services:
  load-balancer:
    build: ./load-balancer
    ports:
      - "18888:18888" # Expose the load load-balancer on port 18811
    profiles:
      - server_group

  rpyc-server1:
    build: ./server
    depends_on:
      - redis
    profiles:
      - server_group
    volumes:
      - ./scripts:/app/scripts
  rpyc-server2:
    build: ./server
    depends_on:
      - redis
    profiles:
      - server_group
    volumes:
      - ./scripts:/app/scripts
  rpyc-server3:
    build: ./server
    depends_on:
      - redis
    profiles:
        - server_group
    volumes:
      - ./scripts:/app/scripts


  rpyc-client:
    build: ./client
    command: ["python", "client.py"]
    profiles:
      - client_group
  rpyc-client2:
    build: ./client
    command: ["python", "client2.py"]
    profiles:
      - client_group
  rpyc-client3:
    build: ./client
    command: ["python", "client3.py"]
    profiles:
      - client_group
  rpyc-client4:
    build: ./client
    command: ["python", "client4.py"]
    profiles:
      - client_group
  rpyc-client5:
    build: ./client
    command: ["python", "client5.py"]
    profiles:
      - client_group

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379" # Expose Redis on port 6379
    profiles:
      - server_group
